AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  log-processing-lambda

  Sample SAM Template for log-processing-lambda

Parameters:
  FilterPattern:
    Type: String
    Default: "[remote_addr,-,remote_user,time_local,request,status,body_bytes_sent,http_referer,http_user_agent]" # Default nginx log pattern.
  LogGroupName:
    Type: String
    Default: "/ecs/sample-website-log-group"
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LogProcessingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: log_processing/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        LogProcessing:
          Type: CloudWatchLogs
          Properties:
            FilterPattern: !Ref FilterPattern
            LogGroupName: !Ref LogGroupName

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LogProcessingFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LogProcessingFunction.Arn
  LogProcessingFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LogProcessingFunctionRole.Arn
